language: c
sudo: true

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe"
    - sudo apt-get update
    - sudo apt-get install -t trusty-backports shellcheck

script:
    - shellcheck -s sh */*/*.sh
