language: c

addons:
    apt:
        packages:
            - cabal-install
            - ghc

install:
    - cabal update
    - cabal install shellcheck

before_script:
    - ~/.cabal/bin/shellcheck -V

script:
    - ~/.cabal/bin/shellcheck -s sh polybar-scripts/*/*.sh
